import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

// Bundles src/gas/ into the single file clasp pushes (gas/main.js).
//
// Apps Script has no module loader and resolves web-app entry points by looking
// up top-level function declarations, so the bundle is an IIFE stored in one
// global and the footer re-declares the entry point as a thin delegate.
const ENTRY_POINTS = ['doPost'];

const GLOBAL_NAME = '__planApi';

const config: esbuild.BuildOptions = {
    entryPoints: ['src/gas/main.ts'],
    outfile: 'gas/main.js',
    bundle: true,
    platform: 'neutral',
    format: 'iife',
    globalName: GLOBAL_NAME,
    // Apps Script's V8 runtime tops out around ES2019.
    target: ['es2019'],
    // The pushed file is what shows up in the Apps Script editor, so keep it
    // readable and keep the Japanese status names as-is rather than escaped.
    minify: false,
    charset: 'utf8',
    legalComments: 'none',
    banner: {
        js: '// Generated by `npm run gas:build` from src/gas/. Do not edit; edit the TypeScript sources.',
    },
    footer: {
        js: ENTRY_POINTS.map((name) => `function ${name}(e) {\n  return ${GLOBAL_NAME}.${name}(e);\n}`).join('\n\n'),
    },
};

const build = (): Promise<esbuild.BuildResult> => {
    return esbuild.build(config);
};

const watch = (): Promise<void> => {
    return esbuild.context(config).then((ctx) => {
        console.log('👀 Watching src/gas for changes...');
        return ctx.watch();
    });
};

export { build, config, watch };

// CLI handling
if (process.argv[1] === fileURLToPath(import.meta.url)) {
    if (process.argv.slice(2).includes('--watch')) {
        watch().catch(console.error);
    } else {
        build().catch(console.error);
    }
}
